name: prestmit
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fade_out_particle: ^1.2.1
  flutter_svg:
  rxdart: ^0.27.5
  smooth_page_indicator: ^1.1.0
  flutter_riverpod: ^2.3.6
  expandable_bottom_sheet: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/inter/Inter-Black.otf
        - asset: lib/assets/fonts/inter/Inter-BlackItalic.otf
        - asset: lib/assets/fonts/inter/Inter-Bold.otf
        - asset: lib/assets/fonts/inter/Inter-BoldItalic.otf
        - asset: lib/assets/fonts/inter/Inter-ExtraBold.otf
        - asset: lib/assets/fonts/inter/Inter-ExtraBoldItalic.otf
        - asset: lib/assets/fonts/inter/Inter-ExtraLight.otf
        - asset: lib/assets/fonts/inter/Inter-ExtraLightItalic.otf
        - asset: lib/assets/fonts/inter/Inter-Italic.otf
        - asset: lib/assets/fonts/inter/Inter-Light.otf
        - asset: lib/assets/fonts/inter/Inter-LightItalic.otf
        - asset: lib/assets/fonts/inter/Inter-Medium.otf
        - asset: lib/assets/fonts/inter/Inter-MediumItalic.otf
        - asset: lib/assets/fonts/inter/Inter-Regular.otf
        - asset: lib/assets/fonts/inter/Inter-SemiBold.otf
        - asset: lib/assets/fonts/inter/Inter-SemiBoldItalic.otf
        - asset: lib/assets/fonts/inter/Inter-Thin.otf
        - asset: lib/assets/fonts/inter/Inter-ThinItalic.otf
        - asset: lib/assets/fonts/inter/Inter-V.ttf

